# docker-compose.yml

version: '3.9'

services:
  # --- Ollama Service for the Local LLM ---
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Youtubot Application Service ---
  app:
    build: .
    container_name: youtubot
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./app.py:/app/app.py
    environment:
      # This tells our app where to find the Ollama service inside the Docker network
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama_data: